name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GPAT }}
        run: |
          git remote add gitlab https://rezny.marek:${GITLAB_TOKEN}@gitlab.fullstackacademy.sk/fsa-rezny/stock-devops.git
          git push --mirror gitlab